"""add repr

Revision ID: 08fd9ac4b641
Revises: 83ba54f28585
Create Date: 2022-12-16 09:59:13.843165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fd9ac4b641'
down_revision = '83ba54f28585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('user_orders_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['orders_id'], ['id'])
        batch_op.drop_column('orders')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_orders_fkey', 'orders', ['orders'], ['id'])
        batch_op.drop_column('orders_id')

    # ### end Alembic commands ###
