"""update relation Product->OrderItem table

Revision ID: 202de4a0400b
Revises: a4cac66067ae
Create Date: 2022-12-16 19:34:30.837903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202de4a0400b'
down_revision = 'a4cac66067ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_orders_fkey', type_='foreignkey')
        batch_op.drop_column('orders')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('product_orders_fkey', 'order_item', ['orders'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
