"""update pop table

Revision ID: 5f3470dd1791
Revises: a356725c1e70
Create Date: 2023-01-03 00:42:04.116367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3470dd1791'
down_revision = 'a356725c1e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proof_of_payment', schema=None) as batch_op:
        batch_op.drop_column('payee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proof_of_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payee', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
