"""update user table

Revision ID: 6baf46d2c73c
Revises: d3d8ae0d70ba
Create Date: 2022-11-24 10:58:25.760830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6baf46d2c73c'
down_revision = 'd3d8ae0d70ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('lname',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('lname',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
