"""better table structure

Revision ID: 83ba54f28585
Revises: d4971c2a858f
Create Date: 2022-12-15 22:14:33.947481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ba54f28585'
down_revision = 'd4971c2a858f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'orders', ['orders_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_order_item_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('orders_customer_id_fkey', type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('order_item_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'orders', ['orders'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('orders')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_customer_id_fkey', 'user', ['customer_id'], ['id'])
        batch_op.create_foreign_key('orders_order_item_id_fkey', 'order_item', ['order_item_id'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('orders_id')

    # ### end Alembic commands ###
