"""add order item table

Revision ID: 905612ed3f8e
Revises: b01d198bc6de
Create Date: 2022-12-14 23:28:23.937783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905612ed3f8e'
down_revision = 'b01d198bc6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'order_item', ['orders'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('orders')

    op.drop_table('order_item')
    # ### end Alembic commands ###
