"""empty message

Revision ID: bc04ea900312
Revises: 8c192d1534dc
Create Date: 2022-11-26 16:49:08.869634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc04ea900312'
down_revision = '8c192d1534dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('regural_price', sa.DECIMAL(), nullable=True),
    sa.Column('discounted_price', sa.DECIMAL(), nullable=True),
    sa.Column('product_rating', sa.DECIMAL(), nullable=True),
    sa.Column('product_review', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
