"""update user table

Revision ID: d3d8ae0d70ba
Revises: 8f174c1161f2
Create Date: 2022-11-24 10:34:46.559360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d8ae0d70ba'
down_revision = '8f174c1161f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('lname', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('zipcode', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=20), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_username_key', ['username'])
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('image')
        batch_op.drop_column('phone')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')

    # ### end Alembic commands ###
