"""update orders table

Revision ID: f7da0bf50466
Revises: ad694e4e9042
Create Date: 2022-12-15 00:00:04.249199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7da0bf50466'
down_revision = 'ad694e4e9042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penerima', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('alamat', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('alamat')
        batch_op.drop_column('penerima')

    # ### end Alembic commands ###
